image: java:8

stages:
  - build
  
before_script:
   - cd recruiter-reports-backend
   - chmod +x mvnw

build:
  stage: build
  script: ./mvnw package
  artifacts:
    paths:
      - target/demo-0.0.1-SNAPSHOT.jar


