image: maven:latest

stages:
  - build

before_script:
  - cd session-management
  - chmod +x mvnw

build:
  stage: build
  script:
    - mvn clean compile assembly:single

  artifacts:
    paths:
      - target/*.jar$
